"""empty message

Revision ID: 0a0a69668390
Revises: 0d6c73611611
Create Date: 2023-05-02 07:50:22.001640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0a69668390'
down_revision = '0d6c73611611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('added_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_key', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plex_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_key', sa.Integer(), nullable=True),
    sa.Column('concat_plex', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('artist_feat', sa.String(), nullable=True),
    sa.Column('grandparent_guid', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('parent_guid', sa.String(), nullable=True),
    sa.Column('parent_index', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('track_index', sa.Integer(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_key', name='_rating_key_uc')
    )
    with op.batch_alter_table('plex_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plex_tracks_concat_plex'), ['concat_plex'], unique=False)
        batch_op.create_index(batch_op.f('ix_plex_tracks_grandparent_guid'), ['grandparent_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_plex_tracks_guid'), ['guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_plex_tracks_parent_guid'), ['parent_guid'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concat_lastfm', sa.String(), nullable=True),
    sa.Column('plex_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plex_id'], ['plex_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concat_lastfm', name='_concat_lastfm_uc')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_concat_lastfm'), ['concat_lastfm'], unique=False)

    op.create_table('scrobbles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concat_lastfm', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('played_at', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash', name='_hash_uc')
    )
    with op.batch_alter_table('scrobbles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrobbles_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrobbles_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrobbles_concat_lastfm'), ['concat_lastfm'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrobbles_track'), ['track'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrobbles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrobbles_track'))
        batch_op.drop_index(batch_op.f('ix_scrobbles_concat_lastfm'))
        batch_op.drop_index(batch_op.f('ix_scrobbles_artist'))
        batch_op.drop_index(batch_op.f('ix_scrobbles_album'))

    op.drop_table('scrobbles')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_concat_lastfm'))

    op.drop_table('matches')
    with op.batch_alter_table('plex_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plex_tracks_parent_guid'))
        batch_op.drop_index(batch_op.f('ix_plex_tracks_guid'))
        batch_op.drop_index(batch_op.f('ix_plex_tracks_grandparent_guid'))
        batch_op.drop_index(batch_op.f('ix_plex_tracks_concat_plex'))

    op.drop_table('plex_tracks')
    op.drop_table('added_tracks')
    # ### end Alembic commands ###
