"""accounts table

Revision ID: 0d6c73611611
Revises: 
Create Date: 2023-04-30 12:17:38.730126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6c73611611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastfm_username', sa.String(), nullable=True),
    sa.Column('lastfm_api_key', sa.String(), nullable=True),
    sa.Column('plex_account_id', sa.Integer(), nullable=True),
    sa.Column('plex_db_file', sa.String(), nullable=True),
    sa.Column('plex_device_id', sa.Integer(), nullable=True),
    sa.Column('plex_music_library_id', sa.Integer(), nullable=True),
    sa.Column('last_hex_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
