"""empty message

Revision ID: b1726077a42f
Revises: 0a0a69668390
Create Date: 2023-05-06 07:55:05.357770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1726077a42f'
down_revision = '0a0a69668390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_plex_id'), ['plex_id'], unique=False)

    with op.batch_alter_table('scrobbles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrobbles_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrobbles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrobbles_match_id'))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_plex_id'))

    # ### end Alembic commands ###
